"""remove example_field from user

Revision ID: 6c26f853a9d2
Revises: a50d34a29d1a
Create Date: 2026-04-06 17:47:10.591738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6c26f853a9d2'
down_revision: Union[str, Sequence[str], None] = 'a50d34a29d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'example_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('example_field', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
